# Generated by Django 4.1.7 on 2023-03-04 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_expiration_time',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
